# Generated by Django 5.2.10 on 2026-01-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars', verbose_name='Аватар'),
        ),
    ]
