# Generated by Django 5.2.10 on 2026-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anons',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Анонс'),
        ),
    ]
